version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      axolotl:
        condition: service_started
    container_name: axolotl-ui-frontend
    image: axolotl-ui-frontend
    environment:
      FLASK_ENV: production
      DOCKER_CONTAINER_NAME: axolotl-ui-backend
      TRAINING_ROOT: /workspace/axolotl-ui/data
      UPLOAD_FOLDER: /workspace/axolotl-ui/data/datasets
      CONFIG_FOLDER: /workspace/axolotl-ui/data/configs
      LOG_FOLDER: /workspace/axolotl-ui/data/logs
      DATABASE_URL: sqlite:////app/instance/app.db
    volumes:
      - ./:/app/
      - ../workspace:/workspace/
      - ../workspace/axolotl-ui/data:/workspace/axolotl-ui/data
      - ./instance:/app/instance
    restart: unless-stopped

  axolotl:
    extends:
      file: docker-compose-axolotl.yaml
      service: axolotl
    volumes:
      - ../workspace/axolotl-ui/data:/workspace/axolotl-ui/data
    depends_on: {}
