version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      axolotl:
        condition: service_started
    container_name: axolotl-ui-frontend
    image: axolotl-ui-frontend
    environment:
      FLASK_ENV: production
      DOCKER_CONTAINER_NAME: axolotl-ui-backend
      TRAINING_ROOT: /workspace/axolotl-ui/data
      UPLOAD_FOLDER: /workspace/axolotl-ui/data/datasets
      CONFIG_FOLDER: /workspace/axolotl-ui/data/configs
      LOG_FOLDER: /workspace/axolotl-ui/data/logs
      DATABASE_URL: sqlite:////app/instance/app.db
      # Point Docker CLI at the socket you just mounted
      DOCKER_HOST: unix:///var/run/docker.sock
      # If using windows containers, use this.
      # DOCKER_HOST: npipe:////./pipe/docker_engine
    volumes:
      - ./:/app/
      - ../workspace:/workspace/
      - ../workspace/axolotl-ui/data:/workspace/axolotl-ui/data
      - ./instance:/app/instance
      # 1. Share the host’s Docker UNIX socket
      - /var/run/docker.sock:/var/run/docker.sock
      # 2. If you are using windows containers, use this.
      #- \\.\pipe\docker_engine:\\.\pipe\docker_engine
    restart: unless-stopped

  axolotl:
    extends:
      file: docker-compose-axolotl.yaml
      service: axolotl
    volumes:
      - ../workspace/axolotl-ui/data:/workspace/axolotl-ui/data
    depends_on: {}
