services:
  axolotl:
    # image: axolotlai/axolotl:main-py3.11-cu128-2.7.0
    container_name: axolotl-ui-backend
    build:
      context: ./
      dockerfile: axolotlDockerFile
    image: axolotl-ui-backend
    volumes:
      - ../workspace/:/workspace/axolotl
      - ../Huggingface/:/root/.cache/huggingface/
    environment:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: tail -f /dev/null
